### PR TITLE
feat(ci): testing40

### PR DESCRIPTION
**Pull request by aali309**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [ ] Read the [contributing guidelines](https://github.com/cryostatio/cryostat/blob/main/CONTRIBUTING.md)
* [ ] Linked a relevant issue which this PR resolves
* [ ] Linked any other relevant issues, PR's, or documentation, if any
* [ ] Resolved all conflicts, if any
* [ ] Rebased your branch PR on top of the latest upstream `main` branch
* [ ] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [ ] [Signed all commits using a GPG signature](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification)

**To recreate commits with GPG signature** `git fetch upstream && git rebase --force --gpg-sign upstream/main`
_______________________________________________

Fixes: #1

## Description of the change:
*This change allows an environment variable to be configured so that...*

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
1. *Run CRYOSTAT_IMAGE=quay.io... sh smoketest.sh...*
2. *...*

### CODE REVIEW

**Comment by aali309** [comment]
@mwangggg please can you take a look at this, I am trying to run the retest-integration test on `pr-ci.yml` file where when /retest is commented it will run the IT tests without building the image.. I know you have done something like this recently. been working on it for a while. Thnx

**Comment by mwangggg** [comment]
https://github.com/aali309/cryostat/blob/6f0bdf45390ce86ae982ab7c40315ff26e20f347/.github/workflows/pr-ci.yml#L157 doesn't need push-to-ghcr
that's why this job isn't being run

**Comment by mwangggg** [comment]
https://github.com/aali309/cryostat/blob/6f0bdf45390ce86ae982ab7c40315ff26e20f347/.github/workflows/ci-build-image.yml#L101C1-L106C49 should be placed in your retest-integration job

**Comment by mwangggg** [comment]
https://github.com/aali309/cryostat/blob/6f0bdf45390ce86ae982ab7c40315ff26e20f347/.github/workflows/pr-ci.yml#L173C1-L173C21 not sure why you're caching here??

**Comment by mwangggg** [comment]
https://github.com/aali309/cryostat/blob/6f0bdf45390ce86ae982ab7c40315ff26e20f347/.github/workflows/pr-ci.yml#L166C1-L166C18 this line will checkout a branch that tracks cryostat/main ... idk if that's quite what you want here

**Pull request merged**
